version: '3'
services:
  web:
    image: crinis/sourcebans:dev
    environment:
      # Enable on install or update and make sure to set this to 'false' afterwards
      # Also set this to false if you made any manual changes to Sourcebans sourcecode you want to keep
      INSTALL: 'true'
    networks:
      - db
    ports: 
    # Change the port before the colon to whatever you want to use
    - 80:8080
    volumes:
      - sourcebans:/var/www/html/
    # You can enable the following three lines to run the container as a different user. For example when using podman.
    #  - sourcebans:/var/www/html/:z
    # user: ${DOCKER_UID:-1000}:${DOCKER_GID:-1000}
    # userns_mode: "keep-id"
  db:
    image: mariadb:10
    environment:
      MYSQL_USER: sourcebans
      MYSQL_PASSWORD: ThisShouldBeAStrongPassword
      MYSQL_DATABASE: sourcebans
      MYSQL_ROOT_PASSWORD: ThisShouldBeAStrongPassword
    volumes:
      - mysql:/var/lib/mysql
    networks:
      - db

networks:
  db:

volumes:
  sourcebans: 
  mysql:
