name: build-sb-dev-branch

on:
  workflow_dispatch: {}
  schedule:
    - cron: "0 2 * * 2"
  push:
    branches:
      - "master"

jobs:
  build:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/sourcebans:sb-dev, ${{ secrets.DOCKERHUB_USERNAME }}/sourcebans:sb-dev-${{ github.run_id }}
          build-args: |
            CHECKOUT=php81
          platforms: linux/amd64, linux/arm64
