name: build-sb-latest-release

on:
  workflow_dispatch: {}
  schedule:
    - cron: '0 0 * * 0'
  push:
    branches:
      - 'master'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      -
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - 
        name: Get latest Sourcebans release
        run: |
          echo "SB_TAG=$(curl https://api.github.com/repos/sbpp/sourcebans-pp/releases -s | jq -r ".[].tag_name" | grep '^1\.7\.[0-9]*$' -m1)" >> $GITHUB_ENV
      -
        name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/sourcebans:sb-${{ env.SB_TAG }}, ${{ secrets.DOCKERHUB_USERNAME }}/sourcebans:sb-latest, ${{ secrets.DOCKERHUB_USERNAME }}/sourcebans:sb-${{ github.run_id }}
          build-args: |
            CHECKOUT=${{ env.SB_TAG }}
